[package]
name = "bevy_magic_fx"
version = "0.2.4"
license = "MIT"
description = "Define mesh-based vfx in serialized files"
edition = "2021" 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
bevy_obj = "0.13"

bevy_common_assets = { version = "0.10", features = ["ron", "toml"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
ron = "0.8.1"


[[example]]
name = "basic"
path = "examples/basic.rs"


[[example]]
name = "enchantment"
path = "examples/enchantment.rs"